"""update hash

Revision ID: 029b30d1897a
Revises: b710c548ab08
Create Date: 2025-10-21 20:34:46.412758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "029b30d1897a"
down_revision: Union[str, Sequence[str], None] = "b710c548ab08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expr_setting_hash",
        existing_type=sa.BINARY(length=32),
        type_=sa.LargeBinary(length=32),
        existing_comment="表达式和设置的哈希",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expr_setting_hash",
        existing_type=sa.LargeBinary(length=32),
        type_=sa.BINARY(length=32),
        existing_comment="表达式和设置的哈希",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
