"""add operators

Revision ID: 071903396219
Revises: 4f2ee39dfeca
Create Date: 2025-10-15 19:17:24.447456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "071903396219"
down_revision: Union[str, Sequence[str], None] = "4f2ee39dfeca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quants_wqb_operator",
        sa.Column("name", sa.VARCHAR(length=127), nullable=False, comment="操作名"),
        sa.Column("category", sa.VARCHAR(length=127), nullable=False, comment="类型名"),
        sa.Column(
            "scope",
            sa.JSON(),
            server_default=sa.text("(json_array())"),
            nullable=False,
            comment="作用域",
        ),
        sa.Column(
            "description",
            sa.VARCHAR(length=511),
            server_default="",
            nullable=False,
            comment="描述",
        ),
        sa.Column(
            "definition",
            sa.VARCHAR(length=511),
            server_default="",
            nullable=False,
            comment="定义",
        ),
        sa.Column(
            "documentation",
            sa.VARCHAR(length=511),
            server_default="",
            nullable=False,
            comment="文档链接",
        ),
        sa.Column(
            "level",
            sa.VARCHAR(length=63),
            server_default="",
            nullable=False,
            comment="级别",
        ),
        sa.Column("id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "quants_wqb_universe",
        sa.Column("name", sa.VARCHAR(length=127), nullable=False, comment="操作名"),
        sa.Column("region", sa.VARCHAR(length=127), nullable=False, comment="地区"),
        sa.Column(
            "delay",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="延迟天数",
        ),
        sa.Column("id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "task_id",
            mysql.INTEGER(unsigned=True),
            server_default="0",
            nullable=False,
            comment="任务ID",
        ),
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_task_id"),
        "quants_wqb_alpha",
        ["task_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quants_wqb_alpha_task_id"), table_name="quants_wqb_alpha")
    op.drop_column("quants_wqb_alpha", "task_id")
    op.drop_table("quants_wqb_universe")
    op.drop_table("quants_wqb_operator")
    # ### end Alembic commands ###
