"""update hash

Revision ID: 0e95d72c88f4
Revises: 029b30d1897a
Create Date: 2025-10-21 20:49:05.060420

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e95d72c88f4"
down_revision: Union[str, Sequence[str], None] = "029b30d1897a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expr_setting_hash",
        existing_type=sa.BINARY(length=32),
        comment="表达式和设置的哈希",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expr_setting_hash",
        existing_type=sa.BINARY(length=32),
        comment=None,
        existing_comment="表达式和设置的哈希",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
