"""add uk

Revision ID: 140d88ea44bd
Revises: a412f7300779
Create Date: 2025-10-25 16:26:20.550066

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "140d88ea44bd"
down_revision: Union[str, Sequence[str], None] = "a412f7300779"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("name"), table_name="quants_wqb_universe")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("name"), "quants_wqb_universe", ["name"], unique=True)
    # ### end Alembic commands ###
