"""update alpha

Revision ID: 1a08d4e7f492
Revises: 20e7acc6f079
Create Date: 2025-10-22 15:15:16.053209

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1a08d4e7f492"
down_revision: Union[str, Sequence[str], None] = "20e7acc6f079"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
