"""update template

Revision ID: 1a096b22c062
Revises: 283fb28a1512
Create Date: 2025-10-30 12:12:06.356627

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1a096b22c062"
down_revision: Union[str, Sequence[str], None] = "283fb28a1512"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_alpha_template",
        sa.Column(
            "default_field",
            sa.JSON(),
            server_default=sa.text("(json_object())"),
            nullable=False,
            comment="默认数据字段",
        ),
    )
    op.add_column(
        "quants_alpha_template",
        sa.Column(
            "operator_count",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="操作符数",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_typ",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="世坤因子类型: 0: regular, 10: sa",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "settings_str",
            sa.VARCHAR(length=511),
            nullable=False,
            comment="参数设置字符串",
        ),
    )
    op.drop_column("quants_wqb_alpha", "setting_str")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "setting_str",
            mysql.VARCHAR(length=511),
            nullable=False,
            comment="参数设置字符串",
        ),
    )
    op.drop_column("quants_wqb_alpha", "settings_str")
    op.drop_column("quants_wqb_alpha", "wqb_typ")
    op.drop_column("quants_alpha_template", "operator_count")
    op.drop_column("quants_alpha_template", "default_field")
    # ### end Alembic commands ###
