"""update alpha

Revision ID: 20e7acc6f079
Revises: e23ad8aa3e01
Create Date: 2025-10-22 15:12:00.714420

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20e7acc6f079"
down_revision: Union[str, Sequence[str], None] = "e23ad8aa3e01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wbq_create_time",
            sa.VARCHAR(length=53),
            sa.Computed(
                "COALESCE(CAST(JSON_EXTRACT(wbq_data, '$.dateCreated') AS VARCHAR(53)), '')",
                persisted=True,
            ),
            nullable=True,
            comment="创建时间",
        ),
    )
    op.drop_index(op.f("expr_setting_hash"), table_name="quants_wqb_alpha")
    op.drop_column("quants_wqb_alpha", "expr_setting_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "expr_setting_hash",
            sa.BINARY(length=32),
            nullable=True,
            comment="表达式和设置的哈希",
        ),
    )
    op.create_index(
        op.f("expr_setting_hash"),
        "quants_wqb_alpha",
        ["expr_setting_hash"],
        unique=True,
    )
    op.drop_column("quants_wqb_alpha", "wbq_create_time")
    # ### end Alembic commands ###
