"""update id

Revision ID: 212ae7f61681
Revises: ca518d341364
Create Date: 2025-10-30 14:41:27.389819

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "212ae7f61681"
down_revision: Union[str, Sequence[str], None] = "ca518d341364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("wqb_alpha_id"), table_name="quants_wqb_alpha")
    op.drop_column("quants_wqb_alpha", "wqb_alpha_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_alpha_id",
            mysql.VARCHAR(length=63),
            nullable=False,
            comment="世坤因子ID",
        ),
    )
    op.create_index(
        op.f("wqb_alpha_id"), "quants_wqb_alpha", ["wqb_alpha_id"], unique=True
    )
    # ### end Alembic commands ###
