"""add mapped typ

Revision ID: 283fb28a1512
Revises: a603247d2bdd
Create Date: 2025-10-28 13:54:23.834693

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "283fb28a1512"
down_revision: Union[str, Sequence[str], None] = "a603247d2bdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_alpha_template",
        sa.Column(
            "typ",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="类型: 0: 未知, 1: 一阶, 2: 二阶, 3: 三阶",
        ),
    )
    op.alter_column(
        "quants_alpha_template",
        "description",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.VARCHAR(length=512),
        existing_comment="描述",
        existing_nullable=False,
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_simulate_time",
            sa.DATETIME(),
            server_default="1900-01-01 00:00:00",
            nullable=False,
            comment="wqb最后一次模拟时间",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_simulate_id",
            sa.VARCHAR(length=63),
            nullable=False,
            comment="世坤模拟ID",
        ),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "parent_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment="父alphaID",
        existing_comment="父模板ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "state",
        existing_type=mysql.TINYINT(display_width=4),
        comment="状态: 0: 初始, 1: 待回测, 5: 测试中, 10: 回测完, 12: 自检完, 15: 审核完, 20: 已激活",
        existing_comment="状态: 0: 未知, 1: 开发中, 2: 测试中, 3: 已上线",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_index(op.f("ix_quants_wqb_alpha_task_id"), table_name="quants_wqb_alpha")
    op.create_index(
        op.f("ix_quants_wqb_alpha_wqb_simulate_id"),
        "quants_wqb_alpha",
        ["wqb_simulate_id"],
        unique=False,
    )
    op.drop_column("quants_wqb_alpha", "task_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "task_id",
            mysql.INTEGER(display_width=10, unsigned=True),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="任务ID",
        ),
    )
    op.drop_index(
        op.f("ix_quants_wqb_alpha_wqb_simulate_id"), table_name="quants_wqb_alpha"
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_task_id"),
        "quants_wqb_alpha",
        ["task_id"],
        unique=False,
    )
    op.alter_column(
        "quants_wqb_alpha",
        "state",
        existing_type=mysql.TINYINT(display_width=4),
        comment="状态: 0: 未知, 1: 开发中, 2: 测试中, 3: 已上线",
        existing_comment="状态: 0: 初始, 1: 待回测, 5: 测试中, 10: 回测完, 12: 自检完, 15: 审核完, 20: 已激活",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "parent_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment="父模板ID",
        existing_comment="父alphaID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("quants_wqb_alpha", "wqb_simulate_id")
    op.drop_column("quants_wqb_alpha", "wqb_simulate_time")
    op.alter_column(
        "quants_alpha_template",
        "description",
        existing_type=sa.VARCHAR(length=512),
        type_=mysql.VARCHAR(length=255),
        existing_comment="描述",
        existing_nullable=False,
    )
    op.drop_column("quants_alpha_template", "typ")
    # ### end Alembic commands ###
