"""add uk

Revision ID: 28ee85ce149b
Revises: 140d88ea44bd
Create Date: 2025-10-25 16:39:38.990687

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "28ee85ce149b"
down_revision: Union[str, Sequence[str], None] = "140d88ea44bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_data_field",
        "description",
        existing_type=mysql.VARCHAR(length=511),
        type_=sa.TEXT(),
        existing_comment="描述",
        existing_nullable=False,
        existing_server_default=sa.text("''"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_data_field",
        "description",
        existing_type=sa.TEXT(),
        type_=mysql.VARCHAR(length=511),
        existing_comment="描述",
        existing_nullable=False,
        existing_server_default=sa.text("''"),
    )
    # ### end Alembic commands ###
