"""update id

Revision ID: 2d0010dcc76d
Revises: f2da381071e0
Create Date: 2025-10-30 13:59:31.147918

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2d0010dcc76d"
down_revision: Union[str, Sequence[str], None] = "f2da381071e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_wqb_alpha_task", "settings_str")
    op.drop_column("quants_wqb_alpha_task", "alpha_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "alpha_hash",
            sa.BINARY(length=32),
            sa.Computed(
                "(unhex(sha2(concat(`expression`,`setting_str`),256)))", persisted=True
            ),
            nullable=True,
            comment="表达式和设置的哈希",
        ),
    )
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "settings_str",
            mysql.VARCHAR(length=511),
            nullable=False,
            comment="参数设置字符串",
        ),
    )
    # ### end Alembic commands ###
