"""update alpha

Revision ID: 2f07de8f048f
Revises: 1a08d4e7f492
Create Date: 2025-10-22 15:17:50.841282

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2f07de8f048f"
down_revision: Union[str, Sequence[str], None] = "1a08d4e7f492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "wbq_create_time",
        existing_type=mysql.VARCHAR(length=53),
        type_=sa.VARCHAR(length=63),
        existing_comment="创建时间",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_wbq_create_time"),
        "quants_wqb_alpha",
        ["wbq_create_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quants_wqb_alpha_wbq_create_time"), table_name="quants_wqb_alpha"
    )
    op.alter_column(
        "quants_wqb_alpha",
        "wbq_create_time",
        existing_type=sa.VARCHAR(length=63),
        type_=mysql.VARCHAR(length=53),
        existing_comment="创建时间",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
