"""add uk

Revision ID: 3027d4db3710
Revises: bffb768a1556
Create Date: 2025-10-25 15:46:41.676226

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3027d4db3710"
down_revision: Union[str, Sequence[str], None] = "bffb768a1556"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_quants_wqb_data_field_category"),
        "quants_wqb_data_field",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quants_wqb_data_field_data_set_id"),
        "quants_wqb_data_field",
        ["data_set_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quants_wqb_data_field_data_set_id"), table_name="quants_wqb_data_field"
    )
    op.drop_index(
        op.f("ix_quants_wqb_data_field_category"), table_name="quants_wqb_data_field"
    )
    # ### end Alembic commands ###
