"""init

Revision ID: 49c7402fe27c
Revises: 
Create Date: 2025-09-26 14:46:13.189572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '49c7402fe27c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quant_alpha_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('title', sa.VARCHAR(length=63), nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='内容'),
    sa.Column('inspiration_id', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='灵感id'),
    sa.Column('var_data', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='反馈内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quant_alpha_template_inspiration_id'), 'quant_alpha_template', ['inspiration_id'], unique=False)
    op.create_table('quant_inspiration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('title', sa.VARCHAR(length=63), nullable=False, comment='标题'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quants_alpha_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('cno', sa.VARCHAR(length=63), nullable=False, comment='世坤编号'),
    sa.Column('expression', sa.VARCHAR(length=511), nullable=False, comment='alpha 表达式'),
    sa.Column('state', mysql.TINYINT(), server_default='0', nullable=False, comment='当前状态: 0: 未上报, 3: 无法上报, 5: 已上报, 8:无法提交, 10: 已提交'),
    sa.Column('typ', mysql.TINYINT(), server_default='0', nullable=False, comment='类型: 0: 未知, 1: 因子, 2: 策略'),
    sa.Column('rate', mysql.TINYINT(), server_default='0', nullable=False, comment='评级'),
    sa.Column('feedback', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='反馈内容'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cno'),
    sa.UniqueConstraint('expression')
    )
    op.create_table('quants_uncommit_alpha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('expression', sa.VARCHAR(length=511), nullable=False, comment='alpha 表达式'),
    sa.Column('state', mysql.TINYINT(), server_default='0', nullable=False, comment='当前状态: 0: 未上报, 3: 无法上报, 5: 已上报'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expression')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quants_uncommit_alpha')
    op.drop_table('quants_alpha_record')
    op.drop_table('quant_inspiration')
    op.drop_index(op.f('ix_quant_alpha_template_inspiration_id'), table_name='quant_alpha_template')
    op.drop_table('quant_alpha_template')
    # ### end Alembic commands ###
