"""update table

Revision ID: 4c32d4e693c9
Revises: cb39175bbe33
Create Date: 2025-10-08 12:44:23.300971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c32d4e693c9'
down_revision: Union[str, Sequence[str], None] = 'cb39175bbe33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quants_alpha_template',
    sa.Column('title', sa.VARCHAR(length=63), nullable=False, comment='标题'),
    sa.Column('inspiration_id', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='灵感ID'),
    sa.Column('expression', sa.TEXT(), server_default='', nullable=False, comment='内容'),
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quants_alpha_template_inspiration_id'), 'quants_alpha_template', ['inspiration_id'], unique=False)
    op.create_table('quants_inspiration',
    sa.Column('title', sa.VARCHAR(length=63), nullable=False, comment='标题'),
    sa.Column('link', sa.VARCHAR(length=511), nullable=False, comment='链接'),
    sa.Column('content', sa.TEXT(), server_default='', nullable=False, comment='内容'),
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quants_wqb_alpha',
    sa.Column('template_id', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='模板ID'),
    sa.Column('expression', sa.VARCHAR(length=511), nullable=False, comment='alpha 表达式'),
    sa.Column('typ', mysql.TINYINT(), server_default='0', nullable=False, comment='类型: 0: 未知, 1: 因子, 2: 策略'),
    sa.Column('region', sa.VARCHAR(length=63), nullable=False, comment='适用市场'),
    sa.Column('universe', sa.VARCHAR(length=63), nullable=False, comment='适用股票池'),
    sa.Column('delay', mysql.TINYINT(), server_default='0', nullable=False, comment='延迟天数'),
    sa.Column('setting_str', sa.VARCHAR(length=511), nullable=False, comment='参数设置字符串'),
    sa.Column('wqb_alpha_id', sa.VARCHAR(length=63), nullable=False, comment='世坤因子ID'),
    sa.Column('state', mysql.TINYINT(), server_default='0', nullable=False, comment='状态: 0: 未知, 1: 开发中, 2: 测试中, 3: 已上线'),
    sa.Column('wbq_data', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='世坤返回的因子数据'),
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expression'),
    sa.UniqueConstraint('expression', 'setting_str', name='uq_expression_setting'),
    sa.UniqueConstraint('wqb_alpha_id')
    )
    op.create_index(op.f('ix_quants_wqb_alpha_template_id'), 'quants_wqb_alpha', ['template_id'], unique=False)
    op.create_table('quants_wqb_alpha_template_task',
    sa.Column('template_id', mysql.INTEGER(unsigned=True), server_default='0', nullable=False, comment='模板ID'),
    sa.Column('field_data', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='字段数据'),
    sa.Column('setting_data', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='设置数据'),
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quants_wqb_alpha_template_task_template_id'), 'quants_wqb_alpha_template_task', ['template_id'], unique=False)
    op.drop_index(op.f('ix_quant_alpha_template_task_template_id'), table_name='quant_alpha_template_task')
    op.drop_table('quant_alpha_template_task')
    op.drop_index(op.f('ix_quant_alpha_template_inspiration_id'), table_name='quant_alpha_template')
    op.drop_table('quant_alpha_template')
    op.drop_table('quant_inspiration')
    op.drop_index(op.f('expression'), table_name='quant_alpha')
    op.drop_index(op.f('ix_quant_alpha_template_id'), table_name='quant_alpha')
    op.drop_index(op.f('uq_expression_setting'), table_name='quant_alpha')
    op.drop_index(op.f('wbq_alpha_id'), table_name='quant_alpha')
    op.drop_table('quant_alpha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quant_alpha',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='数据更新时间'),
    sa.Column('template_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='模板ID'),
    sa.Column('expression', mysql.VARCHAR(length=511), nullable=False, comment='alpha 表达式'),
    sa.Column('typ', mysql.TINYINT(display_width=4), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='类型: 0: 未知, 1: 因子, 2: 策略'),
    sa.Column('region', mysql.VARCHAR(length=63), nullable=False, comment='适用市场'),
    sa.Column('universe', mysql.VARCHAR(length=63), nullable=False, comment='适用股票池'),
    sa.Column('delay', mysql.TINYINT(display_width=4), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='延迟天数'),
    sa.Column('setting_str', mysql.VARCHAR(length=511), nullable=False, comment='参数设置字符串'),
    sa.Column('wbq_alpha_id', mysql.VARCHAR(length=63), nullable=False, comment='世坤因子ID'),
    sa.Column('state', mysql.TINYINT(display_width=4), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='状态: 0: 未知, 1: 开发中, 2: 测试中, 3: 已上线'),
    sa.Column('wbq_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), server_default=sa.text('json_object()'), nullable=False, comment='世坤返回的因子数据'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('wbq_alpha_id'), 'quant_alpha', ['wbq_alpha_id'], unique=True)
    op.create_index(op.f('uq_expression_setting'), 'quant_alpha', ['expression', 'setting_str'], unique=True)
    op.create_index(op.f('ix_quant_alpha_template_id'), 'quant_alpha', ['template_id'], unique=False)
    op.create_index(op.f('expression'), 'quant_alpha', ['expression'], unique=True)
    op.create_table('quant_inspiration',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='数据更新时间'),
    sa.Column('title', mysql.VARCHAR(length=63), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(), server_default=sa.text('json_object()'), nullable=False, comment='内容'),
    sa.Column('link', mysql.VARCHAR(length=511), nullable=False, comment='链接'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quant_alpha_template',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='数据更新时间'),
    sa.Column('title', mysql.VARCHAR(length=63), nullable=False, comment='标题'),
    sa.Column('inspiration_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='灵感ID'),
    sa.Column('content', mysql.TEXT(), server_default=sa.text("''"), nullable=False, comment='内容'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_quant_alpha_template_inspiration_id'), 'quant_alpha_template', ['inspiration_id'], unique=False)
    op.create_table('quant_alpha_template_task',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='数据更新时间'),
    sa.Column('field_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), server_default=sa.text('json_object()'), nullable=False, comment='字段数据'),
    sa.Column('setting_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), server_default=sa.text('json_object()'), nullable=False, comment='设置数据'),
    sa.Column('template_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='模板ID'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_quant_alpha_template_task_template_id'), 'quant_alpha_template_task', ['template_id'], unique=False)
    op.drop_index(op.f('ix_quants_wqb_alpha_template_task_template_id'), table_name='quants_wqb_alpha_template_task')
    op.drop_table('quants_wqb_alpha_template_task')
    op.drop_index(op.f('ix_quants_wqb_alpha_template_id'), table_name='quants_wqb_alpha')
    op.drop_table('quants_wqb_alpha')
    op.drop_table('quants_inspiration')
    op.drop_index(op.f('ix_quants_alpha_template_inspiration_id'), table_name='quants_alpha_template')
    op.drop_table('quants_alpha_template')
    # ### end Alembic commands ###
