"""update column

Revision ID: 4f2ee39dfeca
Revises: 929694736ce1
Create Date: 2025-10-14 14:38:00.310371

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f2ee39dfeca"
down_revision: Union[str, Sequence[str], None] = "929694736ce1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_inspiration",
        sa.Column(
            "link",
            sa.VARCHAR(length=255),
            server_default="",
            nullable=False,
            comment="链接",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_inspiration", "link")
    # ### end Alembic commands ###
