"""add sharp

Revision ID: 51daaae37c00
Revises: 0e95d72c88f4
Create Date: 2025-10-22 10:57:31.174283

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "51daaae37c00"
down_revision: Union[str, Sequence[str], None] = "0e95d72c88f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "sharp",
            sa.DECIMAL(precision=20, scale=8),
            sa.Computed(
                "COALESCE(CAST(JSON_EXTRACT(wbq_data, '$.is.sharp') AS DECIMAL(20,8)), 0)",
                persisted=True,
            ),
            nullable=True,
            comment="夏普比率",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "fitness",
            sa.DECIMAL(precision=20, scale=8),
            sa.Computed(
                "COALESCE(CAST(JSON_EXTRACT(wbq_data, '$.is.fitness') AS DECIMAL(20,8)), 0)",
                persisted=True,
            ),
            nullable=True,
            comment="适应度",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "level", mysql.TINYINT(), server_default="0", nullable=False, comment="级别"
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "pnl_shape",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="收益形态:-1: 异常, 0: 未捕捉, 1: 正常",
        ),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_parent_id"),
        "quants_wqb_alpha",
        ["parent_id"],
        unique=False,
    )
    op.alter_column(
        "quants_wqb_alpha_task",
        "id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "quants_wqb_operator",
        "id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "quants_wqb_universe",
        "id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_universe",
        "id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "quants_wqb_operator",
        "id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "quants_wqb_alpha_task",
        "id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_quants_wqb_alpha_parent_id"), table_name="quants_wqb_alpha")
    op.alter_column(
        "quants_wqb_alpha",
        "id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_column("quants_wqb_alpha", "pnl_shape")
    op.drop_column("quants_wqb_alpha", "level")
    op.drop_column("quants_wqb_alpha", "fitness")
    op.drop_column("quants_wqb_alpha", "sharp")
    # ### end Alembic commands ###
