"""update time

Revision ID: 5205f0bd6886
Revises: 5d87f5ced222
Create Date: 2025-09-28 16:36:15.425583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5205f0bd6886'
down_revision: Union[str, Sequence[str], None] = '5d87f5ced222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quant_alpha_template', sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'))
    op.add_column('quant_alpha_template', sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'))
    op.drop_column('quant_alpha_template', 'created_time')
    op.drop_column('quant_alpha_template', 'updated_time')
    op.add_column('quant_inspiration', sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'))
    op.add_column('quant_inspiration', sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'))
    op.drop_column('quant_inspiration', 'created_time')
    op.drop_column('quant_inspiration', 'updated_time')
    op.add_column('quants_alpha_record', sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'))
    op.add_column('quants_alpha_record', sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'))
    op.drop_column('quants_alpha_record', 'created_time')
    op.drop_column('quants_alpha_record', 'updated_time')
    op.add_column('quants_uncommit_alpha', sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'))
    op.add_column('quants_uncommit_alpha', sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'))
    op.drop_column('quants_uncommit_alpha', 'created_time')
    op.drop_column('quants_uncommit_alpha', 'updated_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quants_uncommit_alpha', sa.Column('updated_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='更新时间'))
    op.add_column('quants_uncommit_alpha', sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='创建时间'))
    op.drop_column('quants_uncommit_alpha', 'update_time')
    op.drop_column('quants_uncommit_alpha', 'create_time')
    op.add_column('quants_alpha_record', sa.Column('updated_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='更新时间'))
    op.add_column('quants_alpha_record', sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='创建时间'))
    op.drop_column('quants_alpha_record', 'update_time')
    op.drop_column('quants_alpha_record', 'create_time')
    op.add_column('quant_inspiration', sa.Column('updated_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='更新时间'))
    op.add_column('quant_inspiration', sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='创建时间'))
    op.drop_column('quant_inspiration', 'update_time')
    op.drop_column('quant_inspiration', 'create_time')
    op.add_column('quant_alpha_template', sa.Column('updated_time', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False, comment='更新时间'))
    op.add_column('quant_alpha_template', sa.Column('created_time', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False, comment='创建时间'))
    op.drop_column('quant_alpha_template', 'update_time')
    op.drop_column('quant_alpha_template', 'create_time')
    # ### end Alembic commands ###
