"""update time

Revision ID: 5d87f5ced222
Revises: 49c7402fe27c
Create Date: 2025-09-26 15:03:10.433010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d87f5ced222'
down_revision: Union[str, Sequence[str], None] = '49c7402fe27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quant_alpha_template', sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'))
    op.add_column('quant_alpha_template', sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'))
    op.drop_column('quant_alpha_template', 'created_at')
    op.drop_column('quant_alpha_template', 'updated_at')
    op.add_column('quant_inspiration', sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'))
    op.add_column('quant_inspiration', sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'))
    op.drop_column('quant_inspiration', 'created_at')
    op.drop_column('quant_inspiration', 'updated_at')
    op.add_column('quants_alpha_record', sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'))
    op.add_column('quants_alpha_record', sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'))
    op.drop_column('quants_alpha_record', 'created_at')
    op.drop_column('quants_alpha_record', 'updated_at')
    op.add_column('quants_uncommit_alpha', sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'))
    op.add_column('quants_uncommit_alpha', sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'))
    op.drop_column('quants_uncommit_alpha', 'created_at')
    op.drop_column('quants_uncommit_alpha', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quants_uncommit_alpha', sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'))
    op.add_column('quants_uncommit_alpha', sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'))
    op.drop_column('quants_uncommit_alpha', 'updated_time')
    op.drop_column('quants_uncommit_alpha', 'created_time')
    op.add_column('quants_alpha_record', sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'))
    op.add_column('quants_alpha_record', sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'))
    op.drop_column('quants_alpha_record', 'updated_time')
    op.drop_column('quants_alpha_record', 'created_time')
    op.add_column('quant_inspiration', sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'))
    op.add_column('quant_inspiration', sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'))
    op.drop_column('quant_inspiration', 'updated_time')
    op.drop_column('quant_inspiration', 'created_time')
    op.add_column('quant_alpha_template', sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'))
    op.add_column('quant_alpha_template', sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'))
    op.drop_column('quant_alpha_template', 'updated_time')
    op.drop_column('quant_alpha_template', 'created_time')
    # ### end Alembic commands ###
