"""update settings

Revision ID: 6bd1af41fcfe
Revises: 73f868f23bfe
Create Date: 2025-10-31 23:16:20.160601

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6bd1af41fcfe"
down_revision: Union[str, Sequence[str], None] = "73f868f23bfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "settings",
            sa.JSON(),
            server_default=sa.text("(json_object())"),
            nullable=False,
            comment="参数设置",
        ),
    )
    op.create_unique_constraint(None, "quants_wqb_alpha", ["expression_hash"])
    op.drop_column("quants_wqb_alpha", "settings_str")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "settings_str",
            mysql.VARCHAR(length=511),
            nullable=False,
            comment="参数设置字符串",
        ),
    )
    op.drop_constraint(None, "quants_wqb_alpha", type_="unique")
    op.drop_column("quants_wqb_alpha", "settings")
    # ### end Alembic commands ###
