"""update id

Revision ID: 73f868f23bfe
Revises: 212ae7f61681
Create Date: 2025-10-30 14:41:47.670242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73f868f23bfe"
down_revision: Union[str, Sequence[str], None] = "212ae7f61681"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_alpha_id",
            sa.VARCHAR(length=63),
            server_default="",
            nullable=False,
            comment="世坤因子ID",
        ),
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_wqb_alpha_id"),
        "quants_wqb_alpha",
        ["wqb_alpha_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quants_wqb_alpha_wqb_alpha_id"), table_name="quants_wqb_alpha"
    )
    op.drop_column("quants_wqb_alpha", "wqb_alpha_id")
    # ### end Alembic commands ###
