"""update id

Revision ID: 7502892e25bc
Revises: b0f40e25cb1f
Create Date: 2025-10-30 13:50:28.344758

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "7502892e25bc"
down_revision: Union[str, Sequence[str], None] = "b0f40e25cb1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_wqb_alpha", "data_field")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "data_field", mysql.VARCHAR(length=511), nullable=False, comment="数据字段"
        ),
    )
    # ### end Alembic commands ###
