"""update hash

Revision ID: 8008d12341de
Revises: e5e4cf01b365
Create Date: 2025-10-21 16:41:36.998205

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8008d12341de"
down_revision: Union[str, Sequence[str], None] = "e5e4cf01b365"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expression",
        existing_type=mysql.VARCHAR(length=511),
        type_=sa.TEXT(),
        existing_comment="alpha 表达式",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expression",
        existing_type=sa.TEXT(),
        type_=mysql.VARCHAR(length=511),
        existing_comment="alpha 表达式",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
