"""update column

Revision ID: 929694736ce1
Revises: 4c32d4e693c9
Create Date: 2025-10-14 14:37:23.423168

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "929694736ce1"
down_revision: Union[str, Sequence[str], None] = "4c32d4e693c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_inspiration", "link")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_inspiration",
        sa.Column("link", mysql.VARCHAR(length=511), nullable=False, comment="链接"),
    )
    # ### end Alembic commands ###
