"""update id

Revision ID: a2e0e364b32d
Revises: 1a096b22c062
Create Date: 2025-10-30 12:48:55.345268

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a2e0e364b32d"
down_revision: Union[str, Sequence[str], None] = "1a096b22c062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_alpha_template",
        "inspiration_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_comment="灵感ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "template_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_comment="模板ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "parent_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_comment="父alphaID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha_task",
        "template_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_comment="模板ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha_task",
        "parent_alpha_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        type_=sa.BIGINT(),
        existing_comment="父因子ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha_task",
        "parent_alpha_id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_comment="父因子ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha_task",
        "template_id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_comment="模板ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "parent_id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_comment="父alphaID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "template_id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_comment="模板ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_alpha_template",
        "inspiration_id",
        existing_type=sa.BIGINT(),
        type_=mysql.INTEGER(display_width=10, unsigned=True),
        existing_comment="灵感ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
