"""add uk

Revision ID: a603247d2bdd
Revises: c7d886e0df7c
Create Date: 2025-10-26 09:12:18.691332

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "a603247d2bdd"
down_revision: Union[str, Sequence[str], None] = "c7d886e0df7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expression_hash",
        existing_type=mysql.VARCHAR(length=63),
        type_=sa.VARCHAR(length=127),
        existing_comment="setting和expression哈希值",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quants_wqb_alpha",
        "expression_hash",
        existing_type=sa.VARCHAR(length=127),
        type_=mysql.VARCHAR(length=63),
        existing_comment="setting和expression哈希值",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
