"""update time

Revision ID: b0f40e25cb1f
Revises: a2e0e364b32d
Create Date: 2025-10-30 13:40:57.797252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b0f40e25cb1f"
down_revision: Union[str, Sequence[str], None] = "a2e0e364b32d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_modified_time",
            sa.DATETIME(),
            server_default="1900-01-01 00:00:00",
            nullable=False,
            comment="wqb最后一次模拟时间",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_submitted_time",
            sa.DATETIME(),
            server_default="1900-01-01 00:00:00",
            nullable=False,
            comment="wqb提交时间",
        ),
    )
    op.drop_column("quants_wqb_alpha", "wqb_simulate_time")
    op.drop_column("quants_wqb_alpha", "wqb_commit_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_commit_time",
            mysql.DATETIME(),
            server_default=sa.text("'1900-01-01 00:00:00'"),
            nullable=False,
            comment="wqb提交时间",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_simulate_time",
            mysql.DATETIME(),
            server_default=sa.text("'1900-01-01 00:00:00'"),
            nullable=False,
            comment="wqb最后一次模拟时间",
        ),
    )
    op.drop_column("quants_wqb_alpha", "wqb_submitted_time")
    op.drop_column("quants_wqb_alpha", "wqb_modified_time")
    # ### end Alembic commands ###
