"""add uk

Revision ID: b39e8adec242
Revises: 28ee85ce149b
Create Date: 2025-10-26 09:04:50.537099

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b39e8adec242"
down_revision: Union[str, Sequence[str], None] = "28ee85ce149b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_wqb_alpha", "batch_no")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "batch_no", mysql.VARCHAR(length=63), nullable=False, comment="批次ID"
        ),
    )
    # ### end Alembic commands ###
