"""update hash

Revision ID: b710c548ab08
Revises: 8008d12341de
Create Date: 2025-10-21 16:46:34.931051

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b710c548ab08"
down_revision: Union[str, Sequence[str], None] = "8008d12341de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "description", sa.TEXT(), server_default="", nullable=False, comment="描述"
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "operator_count",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="操作符数",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_wqb_alpha", "operator_count")
    op.drop_column("quants_wqb_alpha", "description")
    # ### end Alembic commands ###
