"""add uk

Revision ID: b959255238c5
Revises: ea4da56c786b
Create Date: 2025-10-25 15:57:45.011584

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b959255238c5"
down_revision: Union[str, Sequence[str], None] = "ea4da56c786b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_data_field",
        sa.Column(
            "sub_category", sa.VARCHAR(length=127), nullable=False, comment="子类别"
        ),
    )
    op.create_index(
        op.f("ix_quants_wqb_data_field_sub_category"),
        "quants_wqb_data_field",
        ["sub_category"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quants_wqb_data_field_sub_category"),
        table_name="quants_wqb_data_field",
    )
    op.drop_column("quants_wqb_data_field", "sub_category")
    # ### end Alembic commands ###
