"""add field

Revision ID: be1ba2c7d812
Revises: fcd70e42c4f5
Create Date: 2025-10-25 15:20:31.233977

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "be1ba2c7d812"
down_revision: Union[str, Sequence[str], None] = "fcd70e42c4f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quants_wqb_datafield",
        sa.Column("universe", sa.VARCHAR(length=127), nullable=False, comment="操作名"),
        sa.Column("region", sa.VARCHAR(length=127), nullable=False, comment="地区"),
        sa.Column(
            "delay",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="延迟天数",
        ),
        sa.Column("category", sa.VARCHAR(length=127), nullable=False, comment="类别"),
        sa.Column(
            "data_set_id", sa.VARCHAR(length=127), nullable=False, comment="数据集ID"
        ),
        sa.Column("name", sa.VARCHAR(length=127), nullable=False, comment="字段名称"),
        sa.Column(
            "description",
            sa.VARCHAR(length=511),
            server_default="",
            nullable=False,
            comment="描述",
        ),
        sa.Column(
            "typ",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="类型: 0: 未知, 1: matrix, 2: vertor",
        ),
        sa.Column(
            "pyamid_theme_multiplier",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="金字塔主题乘数",
        ),
        sa.Column(
            "coverage",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="覆盖率",
        ),
        sa.Column(
            "users",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="使用该字段的用户数",
        ),
        sa.Column(
            "alphas",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="使用该字段的因子数",
        ),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column("batch_no", sa.VARCHAR(length=63), nullable=False, comment="批次ID"),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "expression_hash",
            sa.VARCHAR(length=63),
            nullable=False,
            comment="setting和expression哈希值",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "data_field", sa.VARCHAR(length=511), nullable=False, comment="数据字段"
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_data",
            sa.JSON(),
            server_default=sa.text("(json_object())"),
            nullable=False,
            comment="世坤返回的因子数据",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_create_time",
            sa.DATETIME(),
            server_default="1900-01-01 00:00:00",
            nullable=False,
            comment="wqb创建时间",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_commit_time",
            sa.DATETIME(),
            server_default="1900-01-01 00:00:00",
            nullable=False,
            comment="wqb提交时间",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_pnl_shape",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="收益形态:-1: 异常, 0: 未捕捉, 1: 正常",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wqb_pnl_data",
            sa.JSON(),
            server_default=sa.text("(json_object())"),
            nullable=False,
            comment="收益数据",
        ),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "parent_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment="父模板ID",
        existing_comment="模板ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "typ",
        existing_type=mysql.TINYINT(display_width=4),
        comment="类型: 0: 未知, 1: 一阶, 2: 二阶, 3: 三阶, 10: 负值模板",
        existing_comment="类型: 0: 未知, 1: 因子, 2: 策略",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "sharpe",
        existing_type=mysql.DECIMAL(precision=20, scale=8),
        nullable=False,
        existing_comment="夏普比率",
    )
    op.alter_column(
        "quants_wqb_alpha",
        "fitness",
        existing_type=mysql.DECIMAL(precision=20, scale=8),
        nullable=False,
        existing_comment="适应度",
    )
    op.drop_index(
        op.f("ix_quants_wqb_alpha_wbq_create_time"), table_name="quants_wqb_alpha"
    )
    op.drop_column("quants_wqb_alpha", "pnl_data")
    op.drop_column("quants_wqb_alpha", "wbq_data")
    op.drop_column("quants_wqb_alpha", "wbq_create_time")
    op.drop_column("quants_wqb_alpha", "pnl_shape")
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "parent_alpha_id",
            mysql.INTEGER(unsigned=True),
            server_default="0",
            nullable=False,
            comment="父因子ID",
        ),
    )
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "data_field", sa.VARCHAR(length=511), nullable=False, comment="数据字段"
        ),
    )
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "typ",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="类型: 0: 未知, 1: 一阶, 2: 二阶, 3: 三阶",
        ),
    )
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "state",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="状态: 0: 未知, 1: 待提交, 2: 提交中, 3: 已完成, 4: 失败",
        ),
    )
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "fail_count",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="失败次数",
        ),
    )
    op.add_column(
        "quants_wqb_alpha_task",
        sa.Column(
            "fail_reason",
            sa.VARCHAR(length=255),
            server_default="",
            nullable=False,
            comment="失败原因",
        ),
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_task_parent_alpha_id"),
        "quants_wqb_alpha_task",
        ["parent_alpha_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quants_wqb_alpha_task_parent_alpha_id"),
        table_name="quants_wqb_alpha_task",
    )
    op.drop_column("quants_wqb_alpha_task", "fail_reason")
    op.drop_column("quants_wqb_alpha_task", "fail_count")
    op.drop_column("quants_wqb_alpha_task", "state")
    op.drop_column("quants_wqb_alpha_task", "typ")
    op.drop_column("quants_wqb_alpha_task", "data_field")
    op.drop_column("quants_wqb_alpha_task", "parent_alpha_id")
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "pnl_shape",
            mysql.TINYINT(display_width=4),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="收益形态:-1: 异常, 0: 未捕捉, 1: 正常",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wbq_create_time",
            mysql.VARCHAR(length=63),
            nullable=True,
            comment="创建时间",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "wbq_data",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            server_default=sa.text("json_object()"),
            nullable=False,
            comment="世坤返回的因子数据",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "pnl_data",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            server_default=sa.text("json_object()"),
            nullable=False,
            comment="收益数据",
        ),
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_wbq_create_time"),
        "quants_wqb_alpha",
        ["wbq_create_time"],
        unique=False,
    )
    op.alter_column(
        "quants_wqb_alpha",
        "fitness",
        existing_type=mysql.DECIMAL(precision=20, scale=8),
        nullable=True,
        existing_comment="适应度",
    )
    op.alter_column(
        "quants_wqb_alpha",
        "sharpe",
        existing_type=mysql.DECIMAL(precision=20, scale=8),
        nullable=True,
        existing_comment="夏普比率",
    )
    op.alter_column(
        "quants_wqb_alpha",
        "typ",
        existing_type=mysql.TINYINT(display_width=4),
        comment="类型: 0: 未知, 1: 因子, 2: 策略",
        existing_comment="类型: 0: 未知, 1: 一阶, 2: 二阶, 3: 三阶, 10: 负值模板",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "quants_wqb_alpha",
        "parent_id",
        existing_type=mysql.INTEGER(display_width=10, unsigned=True),
        comment="模板ID",
        existing_comment="父模板ID",
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("quants_wqb_alpha", "wqb_pnl_data")
    op.drop_column("quants_wqb_alpha", "wqb_pnl_shape")
    op.drop_column("quants_wqb_alpha", "wqb_commit_time")
    op.drop_column("quants_wqb_alpha", "wqb_create_time")
    op.drop_column("quants_wqb_alpha", "wqb_data")
    op.drop_column("quants_wqb_alpha", "data_field")
    op.drop_column("quants_wqb_alpha", "expression_hash")
    op.drop_column("quants_wqb_alpha", "batch_no")
    op.drop_table("quants_wqb_datafield")
    # ### end Alembic commands ###
