"""add field

Revision ID: bffb768a1556
Revises: be1ba2c7d812
Create Date: 2025-10-25 15:28:52.241063

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "bffb768a1556"
down_revision: Union[str, Sequence[str], None] = "be1ba2c7d812"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quants_wqb_data_field",
        sa.Column("universe", sa.VARCHAR(length=127), nullable=False, comment="操作名"),
        sa.Column("region", sa.VARCHAR(length=127), nullable=False, comment="地区"),
        sa.Column(
            "delay",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="延迟天数",
        ),
        sa.Column("category", sa.VARCHAR(length=127), nullable=False, comment="类别"),
        sa.Column(
            "data_set_id", sa.VARCHAR(length=127), nullable=False, comment="数据集ID"
        ),
        sa.Column("name", sa.VARCHAR(length=127), nullable=False, comment="字段名称"),
        sa.Column(
            "description",
            sa.VARCHAR(length=511),
            server_default="",
            nullable=False,
            comment="描述",
        ),
        sa.Column(
            "typ",
            mysql.TINYINT(),
            server_default="0",
            nullable=False,
            comment="类型: 0: 未知, 1: matrix, 2: vertor",
        ),
        sa.Column(
            "pyamid_theme_multiplier",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="金字塔主题乘数",
        ),
        sa.Column(
            "coverage",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="覆盖率",
        ),
        sa.Column(
            "users",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="使用该字段的用户数",
        ),
        sa.Column(
            "alphas",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="使用该字段的因子数",
        ),
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("quants_wqb_datafield")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quants_wqb_datafield",
        sa.Column(
            "universe", mysql.VARCHAR(length=127), nullable=False, comment="操作名"
        ),
        sa.Column("region", mysql.VARCHAR(length=127), nullable=False, comment="地区"),
        sa.Column(
            "delay",
            mysql.TINYINT(display_width=4),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="延迟天数",
        ),
        sa.Column(
            "category", mysql.VARCHAR(length=127), nullable=False, comment="类别"
        ),
        sa.Column(
            "data_set_id", mysql.VARCHAR(length=127), nullable=False, comment="数据集ID"
        ),
        sa.Column(
            "name", mysql.VARCHAR(length=127), nullable=False, comment="字段名称"
        ),
        sa.Column(
            "description",
            mysql.VARCHAR(length=511),
            server_default=sa.text("''"),
            nullable=False,
            comment="描述",
        ),
        sa.Column(
            "typ",
            mysql.TINYINT(display_width=4),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="类型: 0: 未知, 1: matrix, 2: vertor",
        ),
        sa.Column(
            "pyamid_theme_multiplier",
            mysql.DECIMAL(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
            comment="金字塔主题乘数",
        ),
        sa.Column(
            "coverage",
            mysql.DECIMAL(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
            comment="覆盖率",
        ),
        sa.Column(
            "users",
            mysql.DECIMAL(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
            comment="使用该字段的用户数",
        ),
        sa.Column(
            "alphas",
            mysql.DECIMAL(precision=20, scale=8),
            server_default=sa.text("0.00000000"),
            nullable=False,
            comment="使用该字段的因子数",
        ),
        sa.Column(
            "id", mysql.BIGINT(display_width=20), autoincrement=True, nullable=False
        ),
        sa.Column(
            "create_time",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
            comment="数据创建时间",
        ),
        sa.Column(
            "update_time",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
            comment="数据更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("quants_wqb_data_field")
    # ### end Alembic commands ###
