"""add uk

Revision ID: c7d886e0df7c
Revises: b39e8adec242
Create Date: 2025-10-26 09:05:07.683139

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7d886e0df7c"
down_revision: Union[str, Sequence[str], None] = "b39e8adec242"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "batch_no",
            sa.VARCHAR(length=63),
            server_default="",
            nullable=False,
            comment="批次ID",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_wqb_alpha", "batch_no")
    # ### end Alembic commands ###
