"""update id

Revision ID: ca518d341364
Revises: 510c066f294d
Create Date: 2025-10-30 14:32:16.876291

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ca518d341364"
down_revision: Union[str, Sequence[str], None] = "510c066f294d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "sharpe",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="夏普比率",
        ),
    )
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "fitness",
            mysql.DECIMAL(precision=20, scale=8),
            server_default="0.00000000",
            nullable=False,
            comment="适应度",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_wqb_alpha", "fitness")
    op.drop_column("quants_wqb_alpha", "sharpe")
    # ### end Alembic commands ###
