"""remove foreign key

Revision ID: cb39175bbe33
Revises: d606d7ca04ad
Create Date: 2025-10-08 12:28:10.698051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb39175bbe33'
down_revision: Union[str, Sequence[str], None] = 'd606d7ca04ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quant_alpha', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='模板ID',
               existing_nullable=False)
    op.create_index(op.f('ix_quant_alpha_template_id'), 'quant_alpha', ['template_id'], unique=False)
    op.drop_constraint(op.f('quant_alpha_ibfk_1'), 'quant_alpha', type_='foreignkey')
    op.alter_column('quant_alpha_template', 'inspiration_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='灵感ID',
               existing_nullable=False)
    op.create_index(op.f('ix_quant_alpha_template_inspiration_id'), 'quant_alpha_template', ['inspiration_id'], unique=False)
    op.drop_constraint(op.f('quant_alpha_template_ibfk_1'), 'quant_alpha_template', type_='foreignkey')
    op.alter_column('quant_alpha_template_task', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='模板ID',
               existing_nullable=False)
    op.create_index(op.f('ix_quant_alpha_template_task_template_id'), 'quant_alpha_template_task', ['template_id'], unique=False)
    op.drop_constraint(op.f('quant_alpha_template_task_ibfk_1'), 'quant_alpha_template_task', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('quant_alpha_template_task_ibfk_1'), 'quant_alpha_template_task', 'quant_alpha_template', ['template_id'], ['id'])
    op.drop_index(op.f('ix_quant_alpha_template_task_template_id'), table_name='quant_alpha_template_task')
    op.alter_column('quant_alpha_template_task', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='模板ID',
               existing_nullable=False)
    op.create_foreign_key(op.f('quant_alpha_template_ibfk_1'), 'quant_alpha_template', 'quant_inspiration', ['inspiration_id'], ['id'])
    op.drop_index(op.f('ix_quant_alpha_template_inspiration_id'), table_name='quant_alpha_template')
    op.alter_column('quant_alpha_template', 'inspiration_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='灵感ID',
               existing_nullable=False)
    op.create_foreign_key(op.f('quant_alpha_ibfk_1'), 'quant_alpha', 'quant_alpha_template', ['template_id'], ['id'])
    op.drop_index(op.f('ix_quant_alpha_template_id'), table_name='quant_alpha')
    op.alter_column('quant_alpha', 'template_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='模板ID',
               existing_nullable=False)
    # ### end Alembic commands ###
