"""add quant table

Revision ID: d606d7ca04ad
Revises: 1a53563a9dd1
Create Date: 2025-10-01 02:36:47.276939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd606d7ca04ad'
down_revision: Union[str, Sequence[str], None] = '1a53563a9dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quant_alpha_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'),
    sa.Column('title', sa.VARCHAR(length=63), nullable=False, comment='标题'),
    sa.Column('inspiration_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.TEXT(), server_default='', nullable=False, comment='内容'),
    sa.ForeignKeyConstraint(['inspiration_id'], ['quant_inspiration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quant_alpha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('expression', sa.VARCHAR(length=511), nullable=False, comment='alpha 表达式'),
    sa.Column('typ', mysql.TINYINT(), server_default='0', nullable=False, comment='类型: 0: 未知, 1: 因子, 2: 策略'),
    sa.Column('region', sa.VARCHAR(length=63), nullable=False, comment='适用市场'),
    sa.Column('universe', sa.VARCHAR(length=63), nullable=False, comment='适用股票池'),
    sa.Column('delay', mysql.TINYINT(), server_default='0', nullable=False, comment='延迟天数'),
    sa.Column('setting_str', sa.VARCHAR(length=511), nullable=False, comment='参数设置字符串'),
    sa.Column('wbq_alpha_id', sa.VARCHAR(length=63), nullable=False, comment='世坤因子ID'),
    sa.Column('state', mysql.TINYINT(), server_default='0', nullable=False, comment='状态: 0: 未知, 1: 开发中, 2: 测试中, 3: 已上线'),
    sa.Column('wbq_data', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='世坤返回的因子数据'),
    sa.ForeignKeyConstraint(['template_id'], ['quant_alpha_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expression'),
    sa.UniqueConstraint('expression', 'setting_str', name='uq_expression_setting'),
    sa.UniqueConstraint('wbq_alpha_id')
    )
    op.create_table('quant_alpha_template_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='数据创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='数据更新时间'),
    sa.Column('field_data', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='字段数据'),
    sa.Column('setting_data', sa.JSON(), server_default=sa.text('(json_object())'), nullable=False, comment='设置数据'),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['quant_alpha_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quant_inspiration', sa.Column('link', sa.VARCHAR(length=511), nullable=False, comment='链接'))
    op.alter_column('quant_inspiration', 'content',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.TEXT(),
               existing_comment='内容',
               existing_nullable=False,
               existing_server_default=sa.text('json_object()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quant_inspiration', 'content',
               existing_type=sa.TEXT(),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_comment='内容',
               existing_nullable=False,
               existing_server_default=sa.text('json_object()'))
    op.drop_column('quant_inspiration', 'link')
    op.drop_table('quant_alpha_template_task')
    op.drop_table('quant_alpha')
    op.drop_table('quant_alpha_template')
    # ### end Alembic commands ###
