"""add sharp

Revision ID: e23ad8aa3e01
Revises: 51daaae37c00
Create Date: 2025-10-22 10:58:27.343878

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e23ad8aa3e01"
down_revision: Union[str, Sequence[str], None] = "51daaae37c00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "sharpe",
            sa.DECIMAL(precision=20, scale=8),
            sa.Computed(
                "COALESCE(CAST(JSON_EXTRACT(wbq_data, '$.is.sharpe') AS DECIMAL(20,8)), 0)",
                persisted=True,
            ),
            nullable=True,
            comment="夏普比率",
        ),
    )
    op.drop_column("quants_wqb_alpha", "sharp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "sharp",
            mysql.DECIMAL(precision=20, scale=8),
            sa.Computed(
                "(coalesce(cast(json_extract(`wbq_data`,'$.is.sharp') as decimal(20,8)),0))",
                persisted=True,
            ),
            nullable=True,
            comment="夏普比率",
        ),
    )
    op.drop_column("quants_wqb_alpha", "sharpe")
    # ### end Alembic commands ###
