"""update hash

Revision ID: e5e4cf01b365
Revises: fffd1cf7fbc6
Create Date: 2025-10-21 11:34:38.333747

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5e4cf01b365"
down_revision: Union[str, Sequence[str], None] = "fffd1cf7fbc6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "expr_setting_hash",
            sa.BINARY(length=32),
            sa.Computed(
                "UNHEX(SHA2(CONCAT(expression, '||', setting_str), 256))",
                persisted=True,
            ),
            nullable=True,
            comment="表达式和设置的哈希",
        ),
    )
    op.drop_index(op.f("expression"), table_name="quants_wqb_alpha")
    op.drop_index(op.f("uq_expression_setting"), table_name="quants_wqb_alpha")
    op.create_unique_constraint(None, "quants_wqb_alpha", ["expr_setting_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "quants_wqb_alpha", type_="unique")
    op.create_index(
        op.f("uq_expression_setting"),
        "quants_wqb_alpha",
        ["expression", "setting_str"],
        unique=True,
    )
    op.create_index(op.f("expression"), "quants_wqb_alpha", ["expression"], unique=True)
    op.drop_column("quants_wqb_alpha", "expr_setting_hash")
    # ### end Alembic commands ###
