"""add uk

Revision ID: ea4da56c786b
Revises: 3027d4db3710
Create Date: 2025-10-25 15:47:32.281353

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea4da56c786b"
down_revision: Union[str, Sequence[str], None] = "3027d4db3710"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uix_wqb_data_field_unique",
        "quants_wqb_data_field",
        ["region", "universe", "delay", "data_set_id", "name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uix_wqb_data_field_unique", "quants_wqb_data_field", type_="unique"
    )
    # ### end Alembic commands ###
