"""update id

Revision ID: f2da381071e0
Revises: 7502892e25bc
Create Date: 2025-10-30 13:50:39.658699

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2da381071e0"
down_revision: Union[str, Sequence[str], None] = "7502892e25bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quants_wqb_alpha",
        sa.Column(
            "data_field",
            sa.VARCHAR(length=511),
            server_default="",
            nullable=False,
            comment="数据字段",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_wqb_alpha", "data_field")
    # ### end Alembic commands ###
