"""add operators

Revision ID: fffd1cf7fbc6
Revises: 071903396219
Create Date: 2025-10-17 20:51:05.091982

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "fffd1cf7fbc6"
down_revision: Union[str, Sequence[str], None] = "071903396219"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quants_wqb_alpha_task",
        sa.Column(
            "template_id",
            mysql.INTEGER(unsigned=True),
            server_default="0",
            nullable=False,
            comment="模板ID",
        ),
        sa.Column(
            "field_data",
            sa.JSON(),
            server_default=sa.text("(json_object())"),
            nullable=False,
            comment="字段数据",
        ),
        sa.Column(
            "setting_data",
            sa.JSON(),
            server_default=sa.text("(json_object())"),
            nullable=False,
            comment="设置数据",
        ),
        sa.Column("id", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据创建时间",
        ),
        sa.Column(
            "update_time",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="数据更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_task_template_id"),
        "quants_wqb_alpha_task",
        ["template_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_quants_wqb_alpha_template_task_template_id"),
        table_name="quants_wqb_alpha_template_task",
    )
    op.drop_table("quants_wqb_alpha_template_task")
    op.add_column(
        "quants_alpha_template",
        sa.Column(
            "description", sa.VARCHAR(length=255), nullable=False, comment="描述"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quants_alpha_template", "description")
    op.create_table(
        "quants_wqb_alpha_template_task",
        sa.Column(
            "template_id",
            mysql.INTEGER(display_width=10, unsigned=True),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
            comment="模板ID",
        ),
        sa.Column(
            "field_data",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            server_default=sa.text("json_object()"),
            nullable=False,
            comment="字段数据",
        ),
        sa.Column(
            "setting_data",
            mysql.LONGTEXT(charset="utf8mb4", collation="utf8mb4_bin"),
            server_default=sa.text("json_object()"),
            nullable=False,
            comment="设置数据",
        ),
        sa.Column(
            "id",
            mysql.INTEGER(display_width=10, unsigned=True),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "create_time",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=False,
            comment="数据创建时间",
        ),
        sa.Column(
            "update_time",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=False,
            comment="数据更新时间",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_quants_wqb_alpha_template_task_template_id"),
        "quants_wqb_alpha_template_task",
        ["template_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_quants_wqb_alpha_task_template_id"), table_name="quants_wqb_alpha_task"
    )
    op.drop_table("quants_wqb_alpha_task")
    # ### end Alembic commands ###
